---
- hosts: hive-metastore
  tasks:
    - name: restart the hive metastore
      systemd:
        name: hive-metastore
        state: restarted
  tags: ["hive", "hive-metastore"]

- hosts: hive-server
  tasks:
    - name: restart hiveserver2
      systemd:
        name: hive-server2
        state: restarted
  tags: ["hive", "hive-server"]
