---
- hosts: hive-server
  tasks:
    - name: stop hiveserver2
      systemd:
        name: hive-server2
        state: stopped
        enabled: no
  tags: ["hive", "hive-server"]

- hosts: hive-metastore
  tasks:
    - name: stop the hive metastore
      systemd:
        name: hive-metastore
        state: stopped
        enabled: no
  tags: ["hive", "hive-metastore"]
