---
# tasks file for yarn
- name: install {{ yarn_daemon }}
  yum:
    name: "{{ yarn_daemon_name }}"
    state: present

- name: copy out {{ yarn_daemon }} service file
  template:
    src: hadoop-yarn-daemon.service.j2
    dest: /etc/systemd/system/{{ yarn_daemon_name }}.service
    owner: root
    group: root
    mode: 0644

- name: explicitly stop/disable {{ yarn_daemon }}
  systemd:
    name: "{{ yarn_daemon_name }}"
    state: stopped
    enabled: no
